# Generated by Django 6.0.5 on 2026-05-26 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organisations', '0002_organisation_business_type_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organisations.organisation'),
        ),
    ]
