# Generated by Django 6.0.6 on 2026-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='Preferred language for the administration interface.', max_length=2),
        ),
    ]
