# Generated by Django 6.0.7 on 2026-09-19 10:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0001_initial'),
        ('organisations', '0011_alter_organisation_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='GTIN/EAN/UPC del empaque. Vacío para productos sueltos.', max_length=64, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('presentation', models.CharField(blank=True, help_text='Ejemplo: 12 oz, 2 litros, funda de 1 libra.', max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('lb', 'Libra'), ('kg', 'Kilogramo'), ('liter', 'Litro'), ('portion', 'Porción')], default='unit', max_length=20)),
                ('sale_mode', models.CharField(choices=[('unit', 'Por unidad'), ('weight', 'Por peso'), ('amount', 'Por valor en pesos')], default='unit', max_length=20)),
                ('units_per_case', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades que entran en una caja o paquete de compra.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='colmado/products/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'presentation'),
                'indexes': [models.Index(fields=['name', 'brand'], name='colmado_mas_name_cfe695_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('is_quick_sale', models.BooleanField(db_index=True, default=False, help_text='Muestra el producto como botón grande en la pantalla de venta.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_inventory_items', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='colmado.store')),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='colmado.masterproduct')),
            ],
            options={
                'ordering': ('master_product__name',),
                'constraints': [models.UniqueConstraint(fields=('store', 'master_product'), name='unique_master_product_per_colmado_store'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='colmado_inventory_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='colmado_reorder_level_nonnegative'), models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='colmado_cost_price_nonnegative'), models.CheckConstraint(condition=models.Q(('sale_price__gt', 0)), name='colmado_sale_price_positive')],
            },
        ),
    ]
