# Generated by Django 6.0.7 on 2026-09-20 11:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0004_sale_credit_due_date_alter_sale_payment_method_and_more'),
        ('organisations', '0011_alter_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('pay_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='monthly', max_length=20)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_employees', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='colmado.store')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Alquiler'), ('electricity', 'Luz'), ('water', 'Agua'), ('internet', 'Internet y teléfono'), ('transport', 'Transporte'), ('maintenance', 'Mantenimiento'), ('tax', 'Impuestos'), ('other', 'Otro')], db_index=True, default='other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='colmado/expense-receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_expenses', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='colmado.store')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('paid_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_payroll_payments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='colmado.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_payroll_payments', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='colmado.store')),
            ],
            options={
                'ordering': ('-paid_on', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('pay_amount__gt', 0)), name='colmado_employee_pay_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organisation', 'store', 'expense_date'], name='colmado_exp_organis_b55b85_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='colmado_expense_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['organisation', 'store', 'paid_on'], name='colmado_pay_organis_206a0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='colmado_payroll_payment_amount_positive'),
        ),
    ]
