# Generated by Django 6.0.7 on 2026-09-24 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0005_employee_expense_payrollpayment_and_more'),
        ('organisations', '0011_alter_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_suppliers', to='organisations.organisation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ordered', 'Pedida'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_purchase_orders', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='colmado.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='colmado.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('units_per_case', models.PositiveIntegerField(default=1)),
                ('case_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_preferred', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='colmado.masterproduct')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_supplier_products', to='organisations.organisation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='colmado.supplier')),
            ],
            options={
                'ordering': ('master_product__name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Compra recibida'), ('adjustment', 'Ajuste manual')], db_index=True, max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_inventory_movements_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='colmado.inventoryitem')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_inventory_movements', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='colmado.store')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='colmado.purchaseorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'store', 'created_at'], name='colmado_inv_organis_75f70d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='colmado_inventory_movement_quantity_nonzero'), models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='colmado_inventory_movement_after_nonnegative'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='colmado_inventory_movement_cost_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('cases', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('units_per_case', models.PositiveIntegerField()),
                ('case_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='colmado.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colmado.purchaseorder')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('purchase_order', 'inventory_item'), name='unique_inventory_item_per_purchase_order'), models.CheckConstraint(condition=models.Q(('cases__gt', 0)), name='colmado_purchase_order_item_cases_positive'), models.CheckConstraint(condition=models.Q(('units_per_case__gt', 0)), name='colmado_purchase_order_item_units_positive'), models.CheckConstraint(condition=models.Q(('case_cost__gt', 0)), name='colmado_purchase_order_item_case_cost_positive'), models.CheckConstraint(condition=models.Q(('line_total__gt', 0)), name='colmado_purchase_order_item_total_positive'), models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='colmado_purchase_received_quantity_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_colmado_supplier_name_per_organisation'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organisation', 'store', 'status'], name='colmado_pur_organis_6a857a_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='colmado_purchase_order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'master_product'), name='unique_product_per_colmado_supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_case__gt', 0)), name='colmado_supplier_product_units_per_case_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('case_cost__gt', 0)), name='colmado_supplier_product_case_cost_positive'),
        ),
    ]
