# Generated by Django 6.0.7 on 2026-09-24 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0006_supplier_purchaseorder_supplierproduct_and_more'),
        ('organisations', '0011_alter_organisation_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Compra recibida'), ('adjustment', 'Ajuste manual'), ('customer_order', 'Pedido de cliente'), ('customer_order_cancelled', 'Pedido de cliente cancelado')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('public_phone', models.CharField(blank=True, max_length=30)),
                ('public_address', models.CharField(blank=True, max_length=255)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_accepting_orders', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_storefronts', to='organisations.organisation')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='colmado.store')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_phone', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('delivery_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('preparing', 'Preparando'), ('ready', 'Listo'), ('on_the_way', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], db_index=True, default='new', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('inventory_committed', models.BooleanField(db_index=True, default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='colmado.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_customer_orders', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='colmado.store')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='colmado.storefront')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_items', to='colmado.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colmado.customerorder')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('order', 'inventory_item'), name='unique_inventory_item_per_customer_order'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='colmado_customer_order_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='colmado_customer_order_item_price_positive'), models.CheckConstraint(condition=models.Q(('line_total__gt', 0)), name='colmado_customer_order_item_total_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='storefront',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='colmado_storefront_delivery_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='storefront',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order__gte', 0)), name='colmado_storefront_minimum_order_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['organisation', 'store', 'status'], name='colmado_cus_organis_04d171_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.UniqueConstraint(fields=('storefront', 'idempotency_key'), name='unique_customer_order_idempotency_per_storefront'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gt', 0)), name='colmado_customer_order_subtotal_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='colmado_customer_order_delivery_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='colmado_customer_order_total_positive'),
        ),
    ]
