# Generated by Django 6.0.7 on 2026-09-24 11:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0007_alter_inventorymovement_movement_type_storefront_and_more'),
        ('organisations', '0011_alter_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Compra recibida'), ('adjustment', 'Ajuste manual'), ('customer_order', 'Pedido de cliente'), ('customer_order_cancelled', 'Pedido de cliente cancelado'), ('inventory_count', 'Conteo físico'), ('damaged', 'Producto dañado'), ('expired', 'Producto vencido'), ('loss', 'Pérdida o faltante'), ('personal_use', 'Consumo interno'), ('correction', 'Corrección manual')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_inventory_counts_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_inventory_counts', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='colmado.store')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reason', models.CharField(choices=[('regular_count', 'Conteo regular'), ('damaged', 'Producto dañado'), ('expired', 'Producto vencido'), ('loss', 'Pérdida o faltante'), ('personal_use', 'Consumo interno'), ('other', 'Otro')], default='regular_count', max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('counted_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_inventory_items_counted', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_items', to='colmado.inventoryitem')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colmado.inventorycountsession')),
            ],
            options={
                'ordering': ('inventory_item__master_product__name',),
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='inventory_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='colmado.inventorycountsession'),
        ),
        migrations.AddIndex(
            model_name='inventorycountsession',
            index=models.Index(fields=['organisation', 'store', 'status'], name='colmado_inv_organis_fc54a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store',), name='unique_open_inventory_count_per_store'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.UniqueConstraint(fields=('inventory_count', 'inventory_item'), name='unique_item_per_inventory_count'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0)), name='colmado_inventory_count_expected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', 0)), name='colmado_inventory_count_counted_nonnegative'),
        ),
    ]
