# Generated by Django 6.0.7 on 2026-09-25 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0008_alter_inventorymovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_file', models.FileField(upload_to='colmado/catalog-imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida')], db_index=True, default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_products', models.PositiveIntegerField(default=0)),
                ('updated_products', models.PositiveIntegerField(default=0)),
                ('unchanged_products', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_catalog_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('total_rows__gte', 0)), name='colmado_catalog_import_total_rows_nonnegative'), models.CheckConstraint(condition=models.Q(('created_products__gte', 0)), name='colmado_catalog_import_created_nonnegative'), models.CheckConstraint(condition=models.Q(('updated_products__gte', 0)), name='colmado_catalog_import_updated_nonnegative'), models.CheckConstraint(condition=models.Q(('unchanged_products__gte', 0)), name='colmado_catalog_import_unchanged_nonnegative'), models.CheckConstraint(condition=models.Q(('error_rows__gte', 0)), name='colmado_catalog_import_errors_nonnegative')],
            },
        ),
    ]
