# Generated by Django 6.0.7 on 2026-09-25 07:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colmado', '0009_catalogimport'),
        ('organisations', '0011_alter_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=20)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de ventas en efectivo guardado al cerrar la caja.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fondo inicial más ventas en efectivo al cerrar la caja.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado menos efectivo esperado.', max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colmado_cash_register_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colmado_cash_register_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colmado_cash_register_sessions', to='organisations.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_sessions', to='colmado.store')),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_register_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='colmado.cashregistersession'),
        ),
        migrations.AddIndex(
            model_name='cashregistersession',
            index=models.Index(fields=['organisation', 'store', 'opened_at'], name='colmado_cas_organis_6842e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store',), name='unique_open_cash_register_per_store'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount__gte', 0)), name='colmado_cash_opening_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('cash_sales__gte', 0)), name='colmado_cash_sales_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash__gte', 0)), name='colmado_cash_expected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('counted_cash__isnull', True), ('counted_cash__gte', 0), _connector='OR'), name='colmado_cash_counted_nonnegative'),
        ),
    ]
