"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.25.
"""

from pathlib import Path

from environs import Env
import os

BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
env.read_env(BASE_DIR / ".env")

SECRET_KEY = env.str("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "storages",
    "accounts",
    "organisations",
    "subscriptions",
    "auditlogs",
    "core",
    "disco",
    'training',
    "ticketing.apps.TicketingConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DEPLOYED = env.bool("DEPLOYED", default=False)
if DEPLOYED:
    DATABASES = {"default": env.dj_db_url("DATABASE_URL")}
else:
    DATABASES = {
        "default": {
            'ENGINE': env.str("LOCAL_DB_ENGINE"),
            'NAME': env.str("LOCAL_DB_NAME"),
            'USER': env.str("LOCAL_DB_USER"),
            'PASSWORD': env.str("LOCAL_DB_PASSWORD"),
            'HOST': env.str("LOCAL_DB_HOST"),
            'PORT': env.str("LOCAL_DB_PORT"),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "accounts.CustomUser"

# Platform Stripe keys. These remain useful for platform-level payments/subscriptions.
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY")
STRIPE_WEBHOOK_SECRET = env.str("STRIPE_WEBHOOK_SECRET", default="")

# Ticketing online payment integrations.
STRIPE_CONNECT_CLIENT_ID = env.str("STRIPE_CONNECT_CLIENT_ID", default="")
PAYPAL_MODE = env.str("PAYPAL_MODE", default="sandbox")
PAYPAL_CLIENT_ID = env.str("PAYPAL_CLIENT_ID", default="")
PAYPAL_CLIENT_SECRET = env.str("PAYPAL_CLIENT_SECRET", default="")
PAYPAL_WEBHOOK_ID = env.str("PAYPAL_WEBHOOK_ID", default="")

FRONTEND_URL = env.str("FRONTEND_URL", default="http://localhost:5173")
BACKEND_URL = env.str("BACKEND_URL", default="http://localhost:8000")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ]
}

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env.list("CSRF_TRUSTED_ORIGINS", default=[])
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in env.list("CORS_ALLOWED_ORIGINS", default=[])
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

if DEPLOYED:
    SESSION_COOKIE_DOMAIN = env.str("SESSION_COOKIE_DOMAIN", default=".puntacanadiscovery.com")
    CSRF_COOKIE_DOMAIN = env.str("CSRF_COOKIE_DOMAIN", default=".puntacanadiscovery.com")
    SESSION_COOKIE_SAMESITE = env.str("SESSION_COOKIE_SAMESITE", default="None")
    CSRF_COOKIE_SAMESITE = env.str("CSRF_COOKIE_SAMESITE", default="None")
    SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=True)
else:
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_HTTPONLY = True

AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env.str("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env.str("AWS_S3_REGION_NAME", default="us-east-1")
AWS_ACM_REGION = env.str("AWS_ACM_REGION", default="us-east-1")
AWS_CLOUDFRONT_DISTRIBUTION_ID = env.str("AWS_CLOUDFRONT_DISTRIBUTION_ID", default="")
AWS_CLOUDFRONT_DOMAIN = env.str("AWS_CLOUDFRONT_DOMAIN", default="")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {"location": "media"},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Email
EMAIL_BACKEND = env.str(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env.str(
    "DEFAULT_FROM_EMAIL",
    default="Punta Cana Discovery <no-reply@puntacanadiscovery.com>",
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL