# Generated by Django 6.0.5 on 2026-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_employees',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
