"""
SEO Sitemap helpers.

Every sitemap generated by the platform should use these helpers.

This keeps Google, Bing, ChatGPT Search, Claude, Gemini
and every crawler receiving the same canonical URLs.
"""

from django.utils import timezone

from ticketing.models import ExperienceProduct

from .paths import build_product_url


def get_public_products(organisation):
    """
    Returns every indexable product.
    """

    return (
        ExperienceProduct.objects
        .filter(
            organisation=organisation,
            is_active=True,
            public_enabled=True,
            status="active",
        )
        .order_by("-updated_at")
    )


def build_product_sitemap_entries(organisation):
    """
    Returns a list ready to become XML.
    """

    site_settings = getattr(
        organisation,
        "ticketing_public_site_settings",
        None,
    )

    entries = []

    for product in get_public_products(organisation):

        entries.append(
            {
                "loc": build_product_url(
                    product,
                    site_settings,
                ),
                "lastmod": (
                    product.updated_at.date().isoformat()
                    if product.updated_at
                    else timezone.now().date().isoformat()
                ),
                "changefreq": "weekly",
                "priority": "0.90",
            }
        )

    return entries


def build_sitemap_index(organisation):
    """
    Future sitemap index.

    We'll later add:

        products
        blog
        categories
        transfers
        events
        images
    """

    return {
        "products": build_product_sitemap_entries(
            organisation
        ),
    }