# Generated by Django 6.0.5 on 2026-05-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_facilitators', to='training.employee'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_profile', to='training.employee'),
        ),
    ]
