# Generated by Django 6.0.5 on 2026-05-29 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_facilitator_assigned_employees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('service', 'Service'), ('beverage', 'Beverage'), ('culinary', 'Culinary'), ('luxury', 'Luxury'), ('leadership', 'Leadership'), ('hard_rock', 'Hard Rock Standard')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='career_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outlet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='manager',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='attendance_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='expected_attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='training.employee'),
        ),
        migrations.CreateModel(
            name='GuestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_feedback', to='training.employee')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_feedback', to='training.outlet')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.standard'),
        ),
    ]
