# Generated by Django 6.0.5 on 2026-06-01 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisationbranding_organisationdomain'),
        ('training', '0004_employeeevaluation_evaluationquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_employees', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_employee_evaluations', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_evaluations', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_evaluation_answers', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_evaluation_questions', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='evaluationtemplate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_evaluation_templates', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_facilitators', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_guest_feedback', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_outlets', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_roadmap_items', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='standard',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_standards', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='organisations.organisation'),
        ),
    ]
