# Generated by Django 6.0.5 on 2026-06-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_employee_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='assigned_outlets',
            field=models.ManyToManyField(blank=True, related_name='assigned_facilitators', to='training.outlet'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='can_create_employees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='can_create_evaluations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='can_create_trainings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
