# Generated by Django 6.0.5 on 2026-06-16 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_remove_organisation_stripe_customer_id_and_more'),
        ('training', '0006_employee_user_facilitator_assigned_outlets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('visual_poster', 'Visual Poster'), ('microlearning', 'Microlearning'), ('checklist', 'Checklist'), ('facilitator_guide', 'Facilitator Guide')], default='visual_poster', max_length=50)),
                ('incorrect_image', models.ImageField(blank=True, null=True, upload_to='training/resources/incorrect/')),
                ('correct_image', models.ImageField(blank=True, null=True, upload_to='training/resources/correct/')),
                ('short_explanation', models.TextField(blank=True)),
                ('facilitator_notes', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_resources', to='organisations.organisation')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.standard')),
            ],
        ),
        migrations.CreateModel(
            name='StandardRecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_fail_count', models.PositiveIntegerField(default=1)),
                ('reevaluation_after_days', models.PositiveIntegerField(default=3)),
                ('instructions', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_recovery_plans', to='organisations.organisation')),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plan', to='training.standard')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_plans', to='training.trainingresource')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAssignedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reevaluation_pending', 'Re-evaluation Pending'), ('closed', 'Closed')], default='assigned', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reevaluation_due_date', models.DateField(blank=True, null=True)),
                ('reevaluated_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_training_resources', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to='training.employee')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assigned_trainings', to='organisations.organisation')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to='training.standard')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to='training.trainingresource')),
            ],
        ),
    ]
