# Generated by Django 6.0.5 on 2026-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(choices=[('disco', 'Disco'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('store', 'Store'), ('excursions', 'Excursions')], default='disco', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('bartender', 'Bartender'), ('door_staff', 'Door Staff'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=30),
        ),
    ]
