# Generated by Django 6.0.5 on 2026-06-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_business_type_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('platform_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('primary_color', models.CharField(default='#111827', max_length=20)),
                ('secondary_color', models.CharField(default='#6B7280', max_length=20)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=20)),
                ('login_title', models.CharField(blank=True, max_length=255)),
                ('login_subtitle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organisations.organisation')),
            ],
        ),
    ]
