# Generated by Django 6.0.5 on 2026-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisationbranding_organisationdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic - $99/month'), ('pro', 'Pro - $159/month'), ('premium', 'Premium - $199/month')], default='basic', max_length=20),
        ),
    ]
