# Generated by Django 6.0.5 on 2026-06-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisation_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='subscription_status',
        ),
    ]
