# Generated by Django 6.0.6 on 2026-06-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_remove_organisation_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationbranding',
            name='app_description',
            field=models.TextField(blank=True, help_text='Description used in the app manifest'),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='app_icon_192',
            field=models.ImageField(blank=True, help_text='Recommended size: 192x192 PNG', null=True, upload_to='branding/app-icons/'),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='app_icon_512',
            field=models.ImageField(blank=True, help_text='Recommended size: 512x512 PNG', null=True, upload_to='branding/app-icons/'),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='app_short_name',
            field=models.CharField(blank=True, help_text='Short name shown under installed app icon', max_length=50),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='maskable_icon',
            field=models.ImageField(blank=True, help_text='Recommended size: 512x512 PNG with safe padding', null=True, upload_to='branding/app-icons/'),
        ),
        migrations.AddField(
            model_name='organisationbranding',
            name='theme_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisationbranding',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='branding/favicons/'),
        ),
    ]
