# Generated by Django 6.0.6 on 2026-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisationbranding_app_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(choices=[('disco', 'Disco'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('store', 'Store'), ('excursions', 'Excursions'), ('ticketing', 'Tours, Tickets & Transfers')], default='disco', max_length=30),
        ),
    ]
