# Generated by Django 6.0.6 on 2026-07-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch for all AI features in this organisation.')),
                ('translations_enabled', models.BooleanField(default=True, help_text='Allow AI to generate product translations.')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('provider_api_key', models.TextField(blank=True, help_text='Encrypted AI provider API key. Never expose it to the frontend.')),
                ('default_model', models.CharField(default='gpt-5.5', help_text='Default AI model used by this organisation.', max_length=100)),
                ('has_api_key', models.BooleanField(default=False, help_text='Used by the frontend to know whether an API key exists without exposing it.')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation AI Settings',
                'verbose_name_plural': 'Organisation AI Settings',
            },
        ),
    ]
