# Generated by Django 6.0.6 on 2026-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_organisationaisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaisettings',
            name='provider_api_key_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
