# Generated by Django 6.0.7 on 2026-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('facilitator', 'Facilitator'), ('cashier', 'Cashier'), ('bartender', 'Bartender'), ('door_staff', 'Door Staff'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=30),
        ),
    ]
