# Generated by Django 6.0.7 on 2026-09-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(choices=[('disco', 'Disco'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('store', 'Store'), ('excursions', 'Excursions'), ('ticketing', 'Tours, Tickets & Transfers'), ('colmado', 'Colmado')], default='disco', max_length=30),
        ),
    ]
