# Generated by Django 6.0.7 on 2026-09-06 15:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0032_seller_seller_ai_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('default_commission_trigger', models.CharField(choices=[('deposit_paid', 'Deposit paid'), ('fully_paid', 'Fully paid'), ('service_completed', 'Service completed')], default='deposit_paid', max_length=30)),
                ('default_payout_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='monthly', max_length=20)),
                ('google_review_url', models.URLField(blank=True)),
                ('feedback_delay_hours', models.PositiveSmallIntegerField(default=24)),
                ('feedback_channel', models.CharField(choices=[('disabled', 'Disabled'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'WhatsApp and email')], default='disabled', max_length=20)),
                ('feedback_whatsapp_template_name', models.CharField(blank=True, max_length=160)),
                ('feedback_whatsapp_template_language', models.CharField(default='en_US', max_length=20)),
                ('referral_session_hours', models.PositiveSmallIntegerField(default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_network_settings', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('partner_type', models.CharField(choices=[('hotel', 'Hotel'), ('villa', 'Villa'), ('airbnb', 'Airbnb'), ('guesthouse', 'Guesthouse'), ('apartment', 'Apartment'), ('resort', 'Resort'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='hotel', max_length=30)),
                ('product_access_mode', models.CharField(choices=[('inherit', 'Inherit'), ('custom', 'Custom allowlist')], default='inherit', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('payout_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='monthly', max_length=20)),
                ('preferred_payout_method', models.CharField(blank=True, max_length=80)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_partners', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('fixed_per_booking', 'Fixed per booking'), ('fixed_per_guest', 'Fixed per guest'), ('percentage_of_sale', 'Percentage of sale'), ('percentage_of_platform_margin', 'Percentage of platform margin')], max_length=40)),
                ('commission_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('trigger', models.CharField(blank=True, choices=[('deposit_paid', 'Deposit paid'), ('fully_paid', 'Fully paid'), ('service_completed', 'Service completed')], help_text='Blank uses the organisation Partner Network default.', max_length=30)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_rules', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_rules', to='ticketing.experienceproduct')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='partner_network.referralpartner')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rule_snapshot', models.JSONField(default=dict)),
                ('trigger', models.CharField(choices=[('deposit_paid', 'Deposit paid'), ('fully_paid', 'Fully paid'), ('service_completed', 'Service completed')], max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('payable', 'Payable'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to='ticketing.booking')),
                ('booking_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to='ticketing.bookingitem')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to='organisations.organisation')),
                ('commission_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commissions', to='partner_network.referralcommissionrule')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='partner_network.referralpartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_balance_adjustments', to='organisations.organisation')),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_adjustment', to='partner_network.referralcommission')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='partner_network.referralpartner')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPartnerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_view_earnings', models.BooleanField(default=True)),
                ('can_edit_concierge', models.BooleanField(default=True)),
                ('can_download_qr', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_partner_user_access', to='organisations.organisation')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='partner_network.referralpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_partner_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPartnerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=180)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('villa', 'Villa'), ('airbnb', 'Airbnb'), ('guesthouse', 'Guesthouse'), ('apartment', 'Apartment'), ('resort', 'Resort'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='hotel', max_length=30)),
                ('product_access_mode', models.CharField(choices=[('inherit', 'Inherit'), ('custom', 'Custom allowlist')], default='inherit', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('property_information', models.TextField(blank=True)),
                ('concierge_introduction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_partner_locations', to='ticketing.pickuplocation')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='partner_network.referralpartner')),
            ],
            options={
                'ordering': ['partner__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralFeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('disabled', 'Disabled'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'WhatsApp and email')], max_length=20)),
                ('review_url_snapshot', models.URLField(blank=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_feedback_request', to='ticketing.booking')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_feedback_requests', to='organisations.organisation')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_requests', to='partner_network.referralpartner')),
                ('partner_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_requests', to='partner_network.referralpartnerlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referralcommissionrule',
            name='partner_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='partner_network.referralpartnerlocation'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='partner_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='partner_network.referralpartnerlocation'),
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=180)),
                ('internal_note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_payouts', to='organisations.organisation')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_payouts_paid', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='partner_network.referralpartner')),
            ],
            options={
                'ordering': ['-period_end', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPayoutAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount deducted from this payout.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_lines', to='partner_network.referralbalanceadjustment')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_lines', to='partner_network.referralpayout')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_line', to='partner_network.referralcommission')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='partner_network.referralpayout')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_product_access_rules', to='organisations.organisation')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_access_rules', to='partner_network.referralpartner')),
                ('partner_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_access_rules', to='partner_network.referralpartnerlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_access_rules', to='ticketing.experienceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('partner_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='partner_network.referralpartnerlocation')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralQRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(default='qr', max_length=40)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='partner_network.referralqrcode')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_sessions', to='ticketing.customeraiconversation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_sessions', to='organisations.organisation')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sessions', to='partner_network.referralpartner')),
                ('partner_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sessions', to='partner_network.referralpartnerlocation')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_sessions', to='partner_network.referralqrcode')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBookingAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='qr_whatsapp', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attributed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to='ticketing.booking')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_attributions', to='partner_network.referralpartner')),
                ('partner_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_attributions', to='partner_network.referralpartnerlocation')),
                ('referral_qr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_attributions', to='partner_network.referralqrcode')),
                ('referral_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_attributions', to='partner_network.referralsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='referralpartner',
            index=models.Index(fields=['organisation', 'status'], name='partner_net_organis_01e279_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralpartner',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='referral_partner_org_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='referralbalanceadjustment',
            index=models.Index(fields=['organisation', 'partner', 'currency', 'created_at'], name='partner_net_organis_eeb8f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralbalanceadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='referral_balance_adjustment_positive'),
        ),
        migrations.AddIndex(
            model_name='referralpartneraccess',
            index=models.Index(fields=['organisation', 'user', 'is_active'], name='partner_net_organis_5d0508_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralpartneraccess',
            constraint=models.UniqueConstraint(fields=('partner', 'user'), name='referral_partner_user_unique'),
        ),
        migrations.AddIndex(
            model_name='referralpartnerlocation',
            index=models.Index(fields=['partner', 'is_active'], name='partner_net_partner_5731d2_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpartnerlocation',
            index=models.Index(fields=['linked_pickup_location'], name='partner_net_linked__d45f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralfeedbackrequest',
            index=models.Index(fields=['organisation', 'status', 'scheduled_for'], name='partner_net_organis_ca6fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='referralfeedbackrequest',
            index=models.Index(fields=['partner', 'status', 'scheduled_for'], name='partner_net_partner_014b66_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionrule',
            index=models.Index(fields=['organisation', 'is_active', 'effective_from'], name='partner_net_organis_c13681_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionrule',
            index=models.Index(fields=['partner', 'product', 'is_active'], name='partner_net_partner_8e4b57_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['organisation', 'status', 'created_at'], name='partner_net_organis_e87176_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['partner', 'status', 'created_at'], name='partner_net_partner_b2d718_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['booking', 'status'], name='partner_net_booking_281238_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='referral_commission_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='referralpayout',
            index=models.Index(fields=['organisation', 'status', 'period_end'], name='partner_net_organis_cf7c19_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpayout',
            index=models.Index(fields=['partner', 'status', 'period_end'], name='partner_net_partner_4caf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpayoutadjustmentline',
            index=models.Index(fields=['payout', 'created_at'], name='partner_net_payout__86add7_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpayoutadjustmentline',
            index=models.Index(fields=['adjustment', 'created_at'], name='partner_net_adjustm_123a92_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralpayoutadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='referral_payout_adjustment_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='referralpayoutadjustmentline',
            constraint=models.UniqueConstraint(fields=('payout', 'adjustment'), name='referral_payout_adjustment_unique'),
        ),
        migrations.AddIndex(
            model_name='referralpayoutline',
            index=models.Index(fields=['payout', 'created_at'], name='partner_net_payout__4ce701_idx'),
        ),
        migrations.AddIndex(
            model_name='referralproductaccess',
            index=models.Index(fields=['organisation', 'product', 'is_active'], name='partner_net_organis_61c19c_idx'),
        ),
        migrations.AddIndex(
            model_name='referralproductaccess',
            index=models.Index(fields=['partner', 'partner_location', 'is_active'], name='partner_net_partner_342cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='referralqrcode',
            index=models.Index(fields=['partner_location', 'status', 'created_at'], name='partner_net_partner_1cfd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='referralqrscan',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='partner_net_qr_code_7ed2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsession',
            index=models.Index(fields=['organisation', 'conversation', 'status', 'expires_at'], name='partner_net_organis_90e0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsession',
            index=models.Index(fields=['partner', 'partner_location', 'started_at'], name='partner_net_partner_61e08b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralbookingattribution',
            index=models.Index(fields=['partner', 'attributed_at'], name='partner_net_partner_7ecb61_idx'),
        ),
        migrations.AddIndex(
            model_name='referralbookingattribution',
            index=models.Index(fields=['partner_location', 'attributed_at'], name='partner_net_partner_a4ea6a_idx'),
        ),
    ]
