# Generated by Django 6.0.6 on 2026-06-28 11:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='ai_assistant_subtitle',
            field=models.CharField(blank=True, default='Ask anything — best experiences, pickup from your hotel, or quick recommendations.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='ai_assistant_title',
            field=models.CharField(blank=True, default='Meet Your Travel Assistant 🌴', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='card_background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='events_section_subtitle',
            field=models.CharField(blank=True, default='Discover local events, shows and limited-date experiences.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='events_section_title',
            field=models.CharField(blank=True, default='Events', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='excursions_section_subtitle',
            field=models.CharField(blank=True, default='Handpicked adventures you’ll never forget.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='excursions_section_title',
            field=models.CharField(blank=True, default='Top Experiences in Punta Cana', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='final_cta_subtitle',
            field=models.CharField(blank=True, default='Punta Cana Discovery makes booking simple, fast, and secure.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='final_cta_title',
            field=models.CharField(blank=True, default='Ready to Start Your Adventure?', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether the public home hero uses an uploaded image or video.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.45'), help_text='Overlay opacity over the hero media. Example: 0.45.', max_digits=4),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Short subtitle shown under the public home page headline.'),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main headline shown on the public home page.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Optional uploaded hero video for the public home page.', null=True, upload_to='ticketing/public/hero-videos/'),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='Poster image shown before the video loads.', null=True, upload_to='ticketing/public/hero-posters/'),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Optional external hero video URL. Useful for CDN, S3, Spaces or Cloudinary.'),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='homepage_layout_style',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('luxury', 'Luxury'), ('minimal', 'Minimal'), ('adventure', 'Adventure')], default='marketplace', max_length=30),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='muted_text_color',
            field=models.CharField(default='#6B7280', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='nightlife_section_subtitle',
            field=models.CharField(blank=True, default='Nightlife tickets, premium experiences and evening activities.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='nightlife_section_title',
            field=models.CharField(blank=True, default='Nightlife', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='packages_section_subtitle',
            field=models.CharField(blank=True, default='Bundles with better prices — VIP, family and adventure packages.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='packages_section_title',
            field=models.CharField(blank=True, default='Packages & Deals', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='primary_cta_label',
            field=models.CharField(blank=True, default='Explore Experiences', max_length=80),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='secondary_cta_label',
            field=models.CharField(blank=True, default='Book Transfers', max_length=80),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_ai_assistant_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_category_grid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_events_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_excursions_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_final_cta_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_nightlife_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_packages_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_tickets_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_transfers_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='show_trust_badges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='text_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='tickets_section_subtitle',
            field=models.CharField(blank=True, default='Book tickets and attractions with secure reservation options.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='tickets_section_title',
            field=models.CharField(blank=True, default='Tickets & Attractions', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='transfers_section_subtitle',
            field=models.CharField(blank=True, default='Private, reliable rides — airport, hotels and long distance.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='transfers_section_title',
            field=models.CharField(blank=True, default='Transfers', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='trust_badges',
            field=models.JSONField(blank=True, default=list, help_text="Public home trust badges. Example: ['5,000+ Happy Travelers', 'Resort Pickup']."),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='whatsapp_cta_label',
            field=models.CharField(blank=True, default='Chat via WhatsApp', max_length=80),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticketing/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, help_text='If true, this image can be used as the main public cover image.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ticketing.experienceproduct')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='ticketing_p_product_0e369c_idx'), models.Index(fields=['product', 'sort_order'], name='ticketing_p_product_6b6264_idx')],
            },
        ),
    ]
