# Generated by Django 6.0.6 on 2026-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticketingpublicsitesettings_ai_assistant_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_booking_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_order_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_validation_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_availability_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_option_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_variant_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
