# Generated by Django 6.0.6 on 2026-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_booking_external_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='domain_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='domain_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='domain_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('pending_dns', 'Pending DNS'), ('pending_ssl', 'Pending SSL'), ('active', 'Active'), ('failed', 'Failed')], db_index=True, default='not_configured', max_length=30),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='domain_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='Custom public domain for this ticketing website. Example: www.puntacanaticket.com', max_length=255, null=True),
        ),
    ]
