# Generated by Django 6.0.6 on 2026-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticketingpublicsitesettings_domain_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_certificate_arn',
            field=models.CharField(blank=True, help_text='AWS ACM certificate ARN created for this custom domain.', max_length=512),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_certificate_status',
            field=models.CharField(blank=True, help_text='Latest ACM certificate status. Example: PENDING_VALIDATION or ISSUED.', max_length=80),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_validation_record_name',
            field=models.CharField(blank=True, help_text='DNS CNAME name required by ACM validation.', max_length=512),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_validation_record_type',
            field=models.CharField(blank=True, default='CNAME', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_validation_record_value',
            field=models.CharField(blank=True, help_text='DNS CNAME value required by ACM validation.', max_length=512),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='cloudfront_alias_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='cloudfront_distribution_id',
            field=models.CharField(blank=True, help_text='CloudFront distribution ID used to serve this public site.', max_length=120),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='cloudfront_domain_name',
            field=models.CharField(blank=True, help_text='CloudFront target domain. Example: dxxxxx.cloudfront.net', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='dns_records_payload',
            field=models.JSONField(blank=True, default=list, help_text='DNS records shown to the customer so they can paste them in GoDaddy.'),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='domain_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('pending_aws_setup', 'Pending AWS Setup'), ('pending_dns', 'Pending DNS'), ('pending_ssl', 'Pending SSL'), ('pending_cloudfront', 'Pending CloudFront'), ('active', 'Active'), ('failed', 'Failed')], db_index=True, default='not_configured', max_length=30),
        ),
    ]
