# Generated by Django 6.0.6 on 2026-07-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
        ('ticketing', '0005_ticketingpublicsitesettings_aws_acm_certificate_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_capture_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('seller_collected', 'Seller Collected'), ('mixed', 'Mixed'), ('none', 'None')], db_index=True, default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('seller_balance', 'Seller Balance'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketingPaymentProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('none', 'None')], default='none', max_length=20)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('stripe_connect_account_id', models.CharField(blank=True, max_length=255)),
                ('stripe_connect_status', models.CharField(choices=[('not_connected', 'Not Connected'), ('pending', 'Pending'), ('connected', 'Connected'), ('restricted', 'Restricted')], default='not_connected', max_length=30)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=20)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255)),
                ('paypal_merchant_id', models.CharField(blank=True, max_length=255)),
                ('paypal_webhook_id', models.CharField(blank=True, max_length=255)),
                ('payment_success_message', models.CharField(blank=True, default='Payment received. Your booking is confirmed.', max_length=255)),
                ('payment_pending_message', models.CharField(blank=True, default='Your booking was created. Payment is pending confirmation.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_payment_provider_settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Ticketing Payment Provider Settings',
                'verbose_name_plural': 'Ticketing Payment Provider Settings',
            },
        ),
    ]
