# Generated by Django 6.0.6 on 2026-07-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
        ('ticketing', '0006_bookingpayment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365'), ('zoho', 'Zoho Mail'), ('amazon_ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailtrap / Mailgun'), ('custom', 'Custom SMTP')], default='gmail', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10)),
                ('smtp_username', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, help_text='For Gmail use a Google App Password.', max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('send_customer_confirmation', models.BooleanField(default=True)),
                ('send_owner_notification', models.BooleanField(default=True)),
                ('send_receipt_email', models.BooleanField(default=True)),
                ('send_cancellation_email', models.BooleanField(default=True)),
                ('send_review_request_email', models.BooleanField(default=False)),
                ('send_reminder_email', models.BooleanField(default=False)),
                ('connection_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('untested', 'Untested'), ('connected', 'Connected'), ('failed', 'Failed')], default='not_configured', max_length=30)),
                ('last_test_email', models.EmailField(blank=True, max_length=254)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_email_settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Ticketing Email Settings',
                'verbose_name_plural': 'Ticketing Email Settings',
            },
        ),
    ]
