# Generated by Django 6.0.6 on 2026-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_ticketingemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_connection_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_provider_account',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketingemailsettings',
            name='oauth_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketingemailsettings',
            name='provider',
            field=models.CharField(choices=[('google_oauth', 'Google'), ('microsoft_oauth', 'Microsoft 365'), ('zoho', 'Zoho Mail'), ('amazon_ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailtrap / Mailgun'), ('custom', 'Custom SMTP')], default='google_oauth', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketingemailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
