# Generated by Django 6.0.6 on 2026-07-07 13:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
        ('ticketing', '0008_ticketingemailsettings_oauth_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original owner/product price before seller discount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected company/owner revenue after seller commission.', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money actually received by the company/owner.', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_receiver',
            field=models.CharField(choices=[('owner', 'Owner'), ('seller', 'Seller'), ('online_provider', 'Online Provider'), ('mixed', 'Mixed'), ('none', 'None')], db_index=True, default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='seller_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Seller margin/discount allowance used for this booking.', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='settlement_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('partially_settled', 'Partially Settled'), ('settled', 'Settled')], db_index=True, default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='affects_owner_received',
            field=models.BooleanField(default=True, help_text='If true, this payment increases booking.owner_received_amount.'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='affects_seller_collected',
            field=models.BooleanField(default=False, help_text='If true, this payment increases booking.seller_collected_amount.'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='collected_by_party',
            field=models.CharField(choices=[('owner', 'Owner'), ('seller', 'Seller'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank', 'Bank'), ('other', 'Other')], db_index=True, default='owner', help_text='Who actually received the money for this payment.', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='settlement_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('partially_settled', 'Partially Settled'), ('settled', 'Settled')], db_index=True, default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='seller_margin_is_active',
            field=models.BooleanField(default=False, help_text='If enabled, this product margin overrides the seller default margin.'),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='seller_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum seller margin/discount allowance for this product. If 0, the seller default margin may be used.', max_digits=5),
        ),
        migrations.AddField(
            model_name='seller',
            name='can_apply_customer_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='can_keep_commission_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='can_mark_cash_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='can_send_payment_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default seller margin/discount allowance. Example: 15.00 means seller can use up to 15% as customer discount and/or commission.', max_digits=5),
        ),
        migrations.AddField(
            model_name='seller',
            name='max_customer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum customer discount this seller may apply. If 0, the seller margin percent is used as the cap.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='customer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='margin_percent_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='owner_net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organisation', 'settlement_status'], name='ticketing_b_organis_ef1567_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organisation', 'payment_receiver'], name='ticketing_b_organis_707ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['collected_by_party', 'status'], name='ticketing_b_collect_00f6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['settlement_status', 'status'], name='ticketing_b_settlem_937960_idx'),
        ),
    ]
