# Generated by Django 6.0.6 on 2026-07-07 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_booking_customer_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceproduct',
            name='seller_allowed_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum discount/margin allowance seller can use for this product.', max_digits=5),
        ),
    ]
