# Generated by Django 6.0.6 on 2026-07-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_experienceproduct_seller_allowed_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPriceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('min_passengers', models.PositiveIntegerField(default=1)),
                ('max_passengers', models.PositiveIntegerField(default=6)),
                ('vehicle_type', models.CharField(blank=True, choices=[('standard_car', 'Standard Car'), ('suv', 'SUV'), ('van', 'Van'), ('minibus', 'Minibus'), ('bus', 'Bus'), ('luxury', 'Luxury'), ('other', 'Other')], max_length=50)),
                ('one_way_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round_trip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bands', to='ticketing.transferroute')),
            ],
            options={
                'ordering': ['sort_order', 'min_passengers'],
                'indexes': [models.Index(fields=['route', 'is_active'], name='ticketing_t_route_i_248f6c_idx')],
                'unique_together': {('route', 'min_passengers', 'max_passengers')},
            },
        ),
    ]
