# Generated by Django 6.0.6 on 2026-07-09 16:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
        ('ticketing', '0011_transferpriceband'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceproduct',
            name='imported_from_domain',
            field=models.CharField(blank=True, help_text='Original website domain this product was imported from.', max_length=255),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='imported_from_url',
            field=models.URLField(blank=True, help_text='Original product URL from the previous website, used during SEO migration.'),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='preserve_legacy_url',
            field=models.BooleanField(default=True, help_text='If enabled, this product can keep or redirect from its imported legacy URL.'),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='auto_create_product_redirects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='custom_product_url_pattern',
            field=models.CharField(blank=True, help_text='Custom product URL pattern. Must include {slug}. Example: /things-to-do/{slug}', max_length=180),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='preserve_imported_product_urls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingpublicsitesettings',
            name='product_url_pattern',
            field=models.CharField(choices=[('/product/{slug}', 'Product'), ('/products/{slug}', 'Products'), ('/tour/{slug}', 'Tour'), ('/tours/{slug}', 'Tours'), ('/excursion/{slug}', 'Excursion'), ('/excursions/{slug}', 'Excursions'), ('/excursions/detail/{slug}', 'Legacy Excursions Detail'), ('/activity/{slug}', 'Activity'), ('/activities/{slug}', 'Activities'), ('/experience/{slug}', 'Experience'), ('/experiences/{slug}', 'Experiences'), ('custom', 'Custom Pattern')], default='/product/{slug}', help_text='Public product URL pattern. Use {slug}. Example: /excursions/detail/{slug}', max_length=120),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_certificate_arn',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_certificate_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_validation_record_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='aws_acm_validation_record_value',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='cloudfront_distribution_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='cloudfront_domain_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='dns_records_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='hero_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.45'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='ticketing/public/hero-videos/'),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='ticketing/public/hero-posters/'),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketingpublicsitesettings',
            name='trust_badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProductURLAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Path only, not full domain. Example: /excursions/detail/saona-island', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='The preferred public URL for this product.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('redirect_to_primary', models.BooleanField(default=True, help_text='If true, this alias should 301 redirect to the product primary/current URL.')),
                ('redirect_type', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('slug_change', 'Slug Change'), ('pattern_change', 'Pattern Change'), ('legacy', 'Legacy')], db_index=True, default='manual', max_length=30)),
                ('original_full_url', models.URLField(blank=True, help_text='Optional full original URL from the old website.')),
                ('notes', models.TextField(blank=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_product_url_aliases', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_aliases', to='ticketing.experienceproduct')),
            ],
            options={
                'ordering': ['path'],
                'indexes': [models.Index(fields=['organisation', 'path'], name='ticketing_p_organis_f13480_idx'), models.Index(fields=['organisation', 'is_active'], name='ticketing_p_organis_a1fee7_idx'), models.Index(fields=['organisation', 'product'], name='ticketing_p_organis_28ddbc_idx'), models.Index(fields=['organisation', 'source'], name='ticketing_p_organis_497d15_idx')],
                'unique_together': {('organisation', 'path')},
            },
        ),
    ]
