# Generated by Django 6.0.6 on 2026-07-09 23:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_experienceproduct_imported_from_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceproduct',
            name='adult_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='child_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='infant_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='infant_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='experienceproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy/default sell price. Kept for backward compatibility and synced with adult_price.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='experienceproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy/default cost price. Kept for backward compatibility and synced with adult_cost_price.', max_digits=12),
        ),
    ]
