# Generated by Django 6.0.6 on 2026-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_business_type'),
        ('ticketing', '0014_ticketingbusinessentity_productbusinessagreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingWhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta_cloud_api', 'Meta WhatsApp Cloud API')], default='meta_cloud_api', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('meta_app_id', models.CharField(blank=True, max_length=255)),
                ('meta_app_secret', models.CharField(blank=True, max_length=255)),
                ('business_account_id', models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID (WABA ID).', max_length=255)),
                ('phone_number_id', models.CharField(blank=True, help_text='Meta phone number ID used to send WhatsApp messages.', max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('display_phone_number', models.CharField(blank=True, max_length=40)),
                ('verified_business_name', models.CharField(blank=True, max_length=255)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('webhook_subscribed', models.BooleanField(default=False)),
                ('webhook_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_confirmation_template', models.CharField(blank=True, help_text='Approved Meta template name for customer booking confirmations.', max_length=255)),
                ('customer_confirmation_language', models.CharField(default='en_US', max_length=20)),
                ('supplier_booking_template', models.CharField(blank=True, help_text='Approved Meta template name for supplier reservation reports.', max_length=255)),
                ('supplier_booking_language', models.CharField(default='en_US', max_length=20)),
                ('customer_reminder_template', models.CharField(blank=True, help_text='Approved Meta template name for customer booking reminders.', max_length=255)),
                ('customer_reminder_language', models.CharField(default='en_US', max_length=20)),
                ('send_customer_confirmation', models.BooleanField(default=True)),
                ('send_supplier_booking_notification', models.BooleanField(default=True)),
                ('send_customer_reminder', models.BooleanField(default=False)),
                ('attach_customer_ticket', models.BooleanField(default=True)),
                ('attach_supplier_voucher', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('pending', 'Pending'), ('connected', 'Connected'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], db_index=True, default='not_configured', max_length=30)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_recipient', models.CharField(blank=True, max_length=40)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_whatsapp_settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Ticketing WhatsApp Settings',
                'verbose_name_plural': 'Ticketing WhatsApp Settings',
            },
        ),
    ]
