# Generated by Django 6.0.6 on 2026-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_ticketingwhatsappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceproduct',
            name='return_information',
            field=models.TextField(blank=True, help_text='Optional customer-facing return details shown on the ticket. Example: Return buses leave Coco Bongo at 1:00 AM and 2:00 AM.'),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='transport_instructions',
            field=models.TextField(blank=True, help_text='Optional transport or boarding instructions shown on the ticket. Example: After the show, go to the main entrance and present your ticket to the transport coordinator before boarding the assigned bus.'),
        ),
    ]
