# Generated by Django 6.0.6 on 2026-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_experienceproduct_return_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceproduct',
            name='return_information',
        ),
        migrations.RemoveField(
            model_name='experienceproduct',
            name='transport_instructions',
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='ticket_information',
            field=models.TextField(blank=True, help_text="Optional information printed on the customer's ticket. Use this field for return transportation details, meeting points, boarding instructions, dress code, recommendations, important reminders, pickup notes, or any other information the customer should receive after booking."),
        ),
    ]
