# Generated by Django 6.0.6 on 2026-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_remove_experienceproduct_return_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceproduct',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese'), ('de', 'German')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='experienceproduct',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
