# Generated by Django 6.0.7 on 2026-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_experienceproduct_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbusinessagreement',
            name='send_supplier_booking_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbusinessagreement',
            name='supplier_whatsapp_override',
            field=models.CharField(blank=True, help_text='Optional WhatsApp recipient used for this agreement. When blank, the business entity contact WhatsApp is used.', max_length=40),
        ),
        migrations.AddField(
            model_name='ticketingbusinessentity',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Allow automatic booking notifications to this company.'),
        ),
    ]
