# Generated by Django 6.0.7 on 2026-07-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0019_productbusinessagreement_send_supplier_booking_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='Agreement selected when this booking item was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='ticketing.productbusinessagreement'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='business_entity',
            field=models.ForeignKey(blank=True, help_text='Company or supplier responsible for this booking item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='ticketing.ticketingbusinessentity'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='supplier_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='supplier_whatsapp_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
