# Generated by Django 6.0.7 on 2026-08-01 03:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0020_bookingitem_agreement_bookingitem_business_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProductCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_option_id', models.CharField(blank=True, db_index=True, help_text='Stable external option, variant, availability, or ticket ID. Used for Coco Bongo and other external providers.', max_length=150)),
                ('external_option_name', models.CharField(blank=True, help_text='Display name of the external option.', max_length=255)),
                ('rule_type', models.CharField(choices=[('fixed_amount', 'Fixed amount'), ('percentage', 'Percentage')], db_index=True, default='fixed_amount', max_length=30)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed seller allowance. When per-unit is enabled, this amount is multiplied by the booking item quantity.', max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Seller allowance percentage from 0 to 100.', max_digits=5)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_per_unit', models.BooleanField(default=True, help_text='For fixed rules, multiply the amount by the number of tickets or units booked.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_commission_rules', to='ticketing.eventtickettype')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_seller_product_commission_rules', to='organisations.organisation')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_commission_rules', to='ticketing.experiencepackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_commission_rules', to='ticketing.experienceproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commission_rules', to='ticketing.seller')),
            ],
            options={
                'ordering': ['seller__full_name', 'product__name', 'external_option_name', 'id'],
                'indexes': [models.Index(fields=['organisation', 'seller', 'product', 'is_active'], name='ticketing_s_organis_9611fe_idx'), models.Index(fields=['seller', 'product', 'external_option_id'], name='ticketing_s_seller__8369c5_idx'), models.Index(fields=['seller', 'product', 'package'], name='ticketing_s_seller__a56a3a_idx'), models.Index(fields=['seller', 'product', 'event_ticket_type'], name='ticketing_s_seller__46be3e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_ticket_type__isnull', True), ('external_option_id', ''), ('package__isnull', True)), fields=('organisation', 'seller', 'product'), name='ticketing_unique_seller_product_rule'), models.UniqueConstraint(condition=models.Q(('event_ticket_type__isnull', True), ('external_option_id', ''), ('package__isnull', False)), fields=('organisation', 'seller', 'product', 'package'), name='ticketing_unique_seller_package_rule'), models.UniqueConstraint(condition=models.Q(('event_ticket_type__isnull', False), ('external_option_id', ''), ('package__isnull', True)), fields=('organisation', 'seller', 'product', 'event_ticket_type'), name='ticketing_unique_seller_event_rule'), models.UniqueConstraint(condition=models.Q(('event_ticket_type__isnull', True), ('package__isnull', True), models.Q(('external_option_id', ''), _negated=True)), fields=('organisation', 'seller', 'product', 'external_option_id'), name='ticketing_unique_seller_external_rule'), models.CheckConstraint(condition=models.Q(('fixed_amount__gte', Decimal('0.00'))), name='ticketing_seller_rule_fixed_non_negative'), models.CheckConstraint(condition=models.Q(('percentage__gte', Decimal('0.00')), ('percentage__lte', Decimal('100.00'))), name='ticketing_seller_rule_percent_valid')],
            },
        ),
    ]
