# Generated by Django 6.0.7 on 2026-08-01 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0021_sellerproductcommissionrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticketing/blog/categories/')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese'), ('de', 'German')], default='en', max_length=2)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_blog_categories', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, help_text='Optional public author name. Falls back to the linked user.', max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=220)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ticketing/blog/covers/')),
                ('cover_image_alt', models.CharField(blank=True, max_length=255)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese'), ('de', 'German')], default='en', max_length=2)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='ticketing/blog/seo/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('keywords_tags', models.JSONField(blank=True, default=list)),
                ('json_ld_override', models.JSONField(blank=True, default=dict)),
                ('robots_allow_indexing', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketing_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ticketing.blogcategory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_blog_posts', to='organisations.organisation')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_blog_posts', to='ticketing.experienceproduct')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticketing/blog/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ticketing.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Gallery Image',
                'verbose_name_plural': 'Blog Post Gallery Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['organisation', 'is_active', 'sort_order'], name='ticketing_b_organis_3cf4c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogcategory',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='ticketing_unique_blog_category_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['organisation', 'status', 'published_at'], name='ticketing_b_organis_67a785_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['organisation', 'is_active', 'is_featured'], name='ticketing_b_organis_abb0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['organisation', 'category', 'published_at'], name='ticketing_b_organis_778b0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='ticketing_unique_blog_post_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpostgalleryimage',
            index=models.Index(fields=['post', 'is_active', 'sort_order'], name='ticketing_b_post_id_129622_idx'),
        ),
    ]
