# Generated by Django 6.0.7 on 2026-08-14 07:47

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0023_seller_application_status_seller_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webchat', 'Web chat')], max_length=20)),
                ('external_customer_id', models.CharField(help_text='Normalized channel customer identifier; treat as personal data.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('handoff_requested', 'Handoff requested'), ('human_owned', 'Human owned'), ('closed', 'Closed')], default='active', max_length=30)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('travel_start_date', models.DateField(blank=True, null=True)),
                ('travel_end_date', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('adults', models.PositiveSmallIntegerField(default=0)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('last_response_id', models.CharField(blank=True, max_length=255)),
                ('provider_conversation_id', models.CharField(blank=True, max_length=255)),
                ('handoff_category', models.CharField(blank=True, max_length=80)),
                ('handoff_reason', models.TextField(blank=True)),
                ('handoff_requested_at', models.DateTimeField(blank=True, null=True)),
                ('human_owned_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ai_conversations', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerAIHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('category', models.CharField(max_length=80)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.TextField()),
                ('customer_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=512)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('notification_queued_at', models.DateTimeField(blank=True, null=True)),
                ('notification_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_ai_handoffs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='ticketing.customeraiconversation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ai_handoffs', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=20)),
                ('external_message_id', models.CharField(blank=True, max_length=512)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticketing.customeraiconversation')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerItineraryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('token_hash', models.CharField(editable=False, help_text='SHA-256 digest only; never store the public cart token.', max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=512)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('promotion_snapshot', models.JSONField(blank=True, default=list)),
                ('customer_approved', models.BooleanField(default=False)),
                ('customer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('itinerary_revalidated_at', models.DateTimeField(blank=True, null=True)),
                ('age_restrictions_validated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_carts', to='ticketing.customeraiconversation')),
                ('customer_approval_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_itinerary_carts', to='ticketing.customeraimessage')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_itinerary_carts', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerItineraryCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('service_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=0)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('package_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('event_ticket_type_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('selected_external_option_id', models.CharField(blank=True, max_length=255)),
                ('pickup_location_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_name_snapshot', models.CharField(max_length=300)),
                ('option_name_snapshot', models.CharField(blank=True, max_length=300)),
                ('pickup_name_snapshot', models.CharField(blank=True, max_length=300)),
                ('pickup_time_snapshot', models.TimeField(blank=True, null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('availability_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ticketing.customeritinerarycart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_ai_cart_items', to='ticketing.experienceproduct')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='customeraiconversation',
            index=models.Index(fields=['organisation', 'channel', 'external_customer_id'], name='cust_ai_conv_identity_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraiconversation',
            index=models.Index(fields=['organisation', 'status', '-updated_at'], name='cust_ai_conv_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraiconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'handoff_requested', 'human_owned'))), fields=('organisation', 'channel', 'external_customer_id'), name='uniq_open_customer_ai_conv'),
        ),
        migrations.AddConstraint(
            model_name='customeraiconversation',
            constraint=models.CheckConstraint(condition=models.Q(('travel_end_date__isnull', True), ('travel_start_date__isnull', True), ('travel_end_date__gte', models.F('travel_start_date')), _connector='OR'), name='cust_ai_conv_travel_dates_ok'),
        ),
        migrations.AddConstraint(
            model_name='customeraiconversation',
            constraint=models.CheckConstraint(condition=models.Q(('adults__lte', 100), ('children__lte', 100), ('infants__lte', 100)), name='cust_ai_conv_party_counts_ok'),
        ),
        migrations.AddIndex(
            model_name='customeraihandoff',
            index=models.Index(fields=['organisation', 'status', 'priority', 'requested_at'], name='cust_ai_handoff_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraihandoff',
            constraint=models.UniqueConstraint(fields=('organisation', 'idempotency_key'), name='uniq_customer_ai_handoff_key'),
        ),
        migrations.AddIndex(
            model_name='customeraimessage',
            index=models.Index(fields=['conversation', 'occurred_at'], name='cust_ai_msg_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraimessage',
            index=models.Index(fields=['external_message_id'], name='cust_ai_msg_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraimessage',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'inbound'), models.Q(('external_message_id', ''), _negated=True)), fields=('conversation', 'external_message_id'), name='uniq_customer_ai_inbound_msg'),
        ),
        migrations.AddIndex(
            model_name='customeritinerarycart',
            index=models.Index(fields=['organisation', 'status', 'expires_at'], name='cust_ai_cart_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='customeritinerarycart',
            index=models.Index(fields=['conversation', '-updated_at'], name='cust_ai_cart_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycart',
            constraint=models.UniqueConstraint(fields=('organisation', 'idempotency_key'), name='uniq_customer_ai_cart_key'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycart',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('total__gte', 0), ('discount_total__lte', models.F('subtotal'))), name='cust_ai_cart_money_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycart',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_total')))), name='cust_ai_cart_total_reconciles'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'position'), name='uniq_customer_ai_cart_position'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycartitem',
            constraint=models.CheckConstraint(condition=models.Q(('adults__lte', 100), ('children__lte', 100), ('infants__lte', 100), models.Q(('adults__gt', 0), ('children__gt', 0), ('infants__gt', 0), _connector='OR')), name='cust_ai_cart_item_party_ok'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycartitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 0), ('line_subtotal__gte', 0), ('line_discount__gte', 0), ('line_total__gte', 0), ('line_discount__lte', models.F('line_subtotal'))), name='cust_ai_cart_item_money_ok'),
        ),
        migrations.AddConstraint(
            model_name='customeritinerarycartitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('line_subtotal'), '-', models.F('line_discount')))), name='cust_ai_cart_item_reconciles'),
        ),
    ]
