# Generated by Django 6.0.7 on 2026-08-14 10:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0024_customeraiconversation_customeraihandoff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text="Percentage from 0.01 to 100.00, or a fixed amount in the organisation's checkout currency.", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zero means no additional discount cap.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_items', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('minimum_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applies_to_all_products', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Empty means unlimited. Usage is consumed only by checkout.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Maintained atomically by the checkout/booking conversion flow.')),
                ('stackable', models.BooleanField(default=False, help_text='Allow another eligible rule to be evaluated after this rule.')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers are evaluated first.')),
                ('is_public', models.BooleanField(default=True, help_text='Allow this rule to be shown to public customers.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_promotion_rules', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_promotion_rules', to='organisations.organisation')),
                ('products', models.ManyToManyField(blank=True, help_text='Used only when applies_to_all_products is disabled. Products must belong to the same organisation.', related_name='customer_promotion_rules', to='ticketing.experienceproduct')),
            ],
            options={
                'ordering': ('priority', 'id'),
                'indexes': [models.Index(fields=['organisation', 'is_active', 'is_public', 'priority'], name='cust_promo_active_idx'), models.Index(fields=['organisation', 'valid_from', 'valid_until'], name='cust_promo_window_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='cust_promo_discount_positive'), models.CheckConstraint(condition=models.Q(('discount_type', 'fixed_amount'), ('discount_value__lte', 100), _connector='OR'), name='cust_promo_percent_lte_100'), models.CheckConstraint(condition=models.Q(('max_discount_amount__gte', 0), ('minimum_subtotal__gte', 0)), name='cust_promo_money_nonnegative'), models.CheckConstraint(condition=models.Q(('minimum_items__gte', 1), ('minimum_items__lte', 12)), name='cust_promo_item_count_valid'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='cust_promo_window_valid'), models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('times_used__lte', models.F('max_uses')), _connector='OR'), name='cust_promo_usage_valid')],
            },
        ),
    ]
