# Generated by Django 6.0.7 on 2026-08-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0025_customerpromotionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritinerarycart',
            name='converted_booking',
            field=models.OneToOneField(blank=True, help_text='Booking created from this cart. This relationship prevents duplicate cart conversion and preserves the audit trail.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ai_source_cart', to='ticketing.booking'),
        ),
    ]
