# Generated by Django 6.0.7 on 2026-08-26 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationaisettings_provider_api_key_last_updated'),
        ('ticketing', '0028_alter_bookingpayment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingCustomerAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shadow_mode', models.BooleanField(default=True, help_text='Generate and store AI replies without sending them to the customer.')),
                ('max_tool_calls', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('max_reply_characters', models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(1200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_customer_ai_settings', to='organisations.organisation')),
            ],
        ),
    ]
