# Generated by Django 6.0.7 on 2026-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0029_ticketingcustomeraisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='agent_display_name',
            field=models.CharField(default='Travel Assistant', max_length=80),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='allow_cart_session_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='allow_itinerary_recommendations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='human_handoff_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='sales_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='selling_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='supported_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketingcustomeraisettings',
            name='tone',
            field=models.CharField(default='warm, helpful, concise, and professional', max_length=200),
        ),
    ]
