# Generated by Django 6.0.7 on 2026-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0030_ticketingcustomeraisettings_agent_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingpaymentprovidersettings',
            name='default_customer_payment_choice',
            field=models.CharField(choices=[('full', 'Pay in full online'), ('deposit', 'Pay deposit online'), ('pending', 'Reserve now and pay later'), ('cash', 'Pay in person')], default='full', help_text='The only payment choice presented to public checkout customers for this organisation.', max_length=20),
        ),
    ]
