# Generated by Django 6.0.7 on 2026-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0031_ticketingpaymentprovidersettings_default_customer_payment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_ai_enabled',
            field=models.BooleanField(default=True, help_text='Allow this individual seller to use the AI Booking Assistant.'),
        ),
    ]
