# Generated by Django 6.0.7 on 2026-09-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0032_seller_seller_ai_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seller_credit_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seller_credit_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_collection', 'Pending Collection'), ('settled', 'Paid To Company'), ('blocked', 'Not Paid / Blocked')], db_index=True, default='not_applicable', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='seller_credit_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seller_credit_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketing_seller_credit_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
