# Generated by Django 6.0.6 on 2026-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0003_product_brand_product_is_alcohol_product_size_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoemployee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='disco/employees/'),
        ),
    ]
