# Generated by Django 6.0.6 on 2026-06-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0004_discoemployee_photo'),
        ('organisations', '0006_organisationbranding_app_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoemployee',
            name='daily_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily employee payment used for payroll reports.', max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage applied to sales. Example: 18.00', max_digits=5)),
                ('currency_symbol', models.CharField(default='RD$', help_text='Display-only currency symbol. No currency conversion is applied.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disco_settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Disco Settings',
                'verbose_name_plural': 'Disco Settings',
            },
        ),
    ]
