# Generated by Django 6.0.6 on 2026-06-24 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0005_discoemployee_daily_pay_discosettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Accounting date used for daily reports, monthly reports, and closing.'),
        ),
    ]
