# Generated by Django 6.0.6 on 2026-06-24 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0006_alter_expense_options_expense_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoemployee',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the employee stopped working. Empty means currently active.', null=True),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date when the employee started working.'),
        ),
    ]
