# Generated by Django 6.0.6 on 2026-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0007_discoemployee_end_date_discoemployee_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoemployee',
            name='can_access_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_access_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_apply_discounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_cancel_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_close_cash_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_reservations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_manage_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_open_cash_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_view_activity_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoemployee',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
